- name: Creating polybar versioned directory
  become: yes
  file:
    path: /opt/polybar-{{ polybar_git_version }}/
    state: directory
    mode: 0755

- name: Downloading polybar
  become: yes
  unarchive:
    src: https://github.com/polybar/polybar/releases/download/{{ polybar_git_version }}/polybar-{{ polybar_git_version }}.tar
    dest: /opt/polybar-{{ polybar_git_version }}/
    extra_opts:
      - --strip-components=1
    remote_src: yes

- name: Creating build directory
  become: yes
  file:
    path: /opt/polybar-{{ polybar_git_version }}/build
    state: directory
    mode: 0755

- name: Cmake polybar
  become: yes
  command: /usr/bin/cmake -DCMAKE_EXE_LINKER_FLAGS="-Wl,-rpath,/usr/local/gcc/8.3.0/lib64,-rpath,/usr/local/gcc/8.3.0/lib" ..
  changed_when: false
  args:
    chdir: /opt/polybar-{{ polybar_git_version }}/build/
  environment: "{{ gcc_env }}"

- name: Make polybar
  become: yes
  make:
    chdir: /opt/polybar-{{ polybar_git_version }}/build/
    params:
      NUM_THREADS: 4
  environment: "{{ gcc_env }}"

- name: Install polybar
  become: yes
  make:
    chdir: /opt/polybar-{{ polybar_git_version }}/build/
    target: install
