- name: Creating polybar versioned directory
  become: yes
  file:
    path: /opt/polybar-{{ polybar_git_version }}/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Downloading polybar
  become: yes
  unarchive:
    src: https://github.com/polybar/polybar/releases/download/{{ polybar_git_version }}/polybar-{{ polybar_git_version }}.tar
    dest: /opt/polybar-{{ polybar_git_version }}/
    extra_opts: 
      - --strip-components=1
    remote_src: yes

- name: Creating build directory
  become: yes
  file:
    path: /opt/polybar-{{ polybar_git_version }}/build
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Cmake polybar
  shell: cmake ..
  args:
    chdir: /opt/polybar-{{ polybar_git_version }}/build/

- name: Make polybar
  make:
    chdir: /opt/polybar-{{ polybar_git_version }}/build/ # required. cd into this directory before running make
    params: -j4 # not required. Any extra parameters to pass to make

- name: Install polybar
  make: make -j$(nproc)
    chdir: /opt/polybar-{{ polybar_git_version }}/build/
    target: install

# sudo unlink /lib64/libstdc++.so.6
# sudo ln -s /usr/local/lib64/libstdc++.so.6.0.25 /lib64/libstdc++.so.6
