- name: Creating polybar versioned directory
  become: yes
  file:
    path: /opt/polybar-{{ polybar_git_version }}/
    state: directory
    mode: 0755

- name: Downloading polybar
  become: yes
  unarchive:
    src: https://github.com/polybar/polybar/releases/download/{{ polybar_git_version }}/polybar-{{ polybar_git_version }}.tar
    dest: /opt/polybar-{{ polybar_git_version }}/
    extra_opts: 
      - --strip-components=1
    remote_src: yes

- name: Creating build directory
  become: yes
  file:
    path: /opt/polybar-{{ polybar_git_version }}/build
    state: directory
    mode: 0755

- name: Cmake polybar
  become: yes
  shell: cmake ..
  args:
    chdir: /opt/polybar-{{ polybar_git_version }}/build/

- name: Make polybar
  become: yes
  make:
    chdir: /opt/polybar-{{ polybar_git_version }}/build/
    params:
      NUM_THREADS: 4

- name: Install polybar
  become: yes
  make:
    chdir: /opt/polybar-{{ polybar_git_version }}/build/
    target: install

# sudo unlink /lib64/libstdc++.so.6
# sudo ln -s /usr/local/lib64/libstdc++.so.6.0.25 /lib64/libstdc++.so.6
