- name: Creating polybar versioned directory
  become: yes
  file:
    path: /opt/polybar-{{ polybar_git_version }}/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Downloading polybar
  become: yes
  unarchive:
    src: https://github.com/polybar/polybar/releases/download/{{ polybar_git_version }}/polybar-{{ polybar_git_version }}.tar
    dest: /opt/polybar-{{ polybar_git_version }}/
    extra_opts: 
      - --strip-components=1
    remote_src: yes

- name: Creating build directory
  become: yes
  file:
    path: /opt/polybar-{{ polybar_git_version }}/build
    state: directory
    owner: root
    group: root
    mode: 0755
  
# sudo unlink /lib64/libstdc++.so.6
# sudo ln -s /usr/local/lib64/libstdc++.so.6.0.25 /lib64/libstdc++.so.6
